In [2]:
from googleapiclient.discovery import build
import pandas as pd

API_KEY = "AIzaSyDppAtpVZwXITRCKy2Txd-KZxlNiBj8xi4"
youtube = build("youtube", "v3", developerKey=API_KEY)


def get_video_ids(channel_id, youtube):

  channel_data = []

  request1 = youtube.channels().list(
      id = channel_id,
      part = 'contentDetails'
  )

  response1 = request1.execute()
  upload_key = response1['items'][0]['contentDetails']['relatedPlaylists']['uploads']

  request2 = youtube.playlistItems().list(
      playlistId = upload_key,
      part = 'snippet',
      maxResults = 200
  )

  response2 = request2.execute()
  for i in range(0, 200):
    try:
      channel_data.append(response2['items'][i]['snippet']['resourceId']['videoId'])
    except:
      return channel_data

video_id_sam = get_video_ids('UC1DTYW241WD64ah5BFWn4JA',youtube)
video_id_sam

['5L5tjscy85U',
 '4vvk7i-M6V0',
 'FJwMDVrg8WU',
 'wQmKqqsS-vs',
 'XKRW1zgkCVc',
 'zz0PYzzfixY',
 'ChSUvdU_Sbk',
 '7s6VfSOuZpQ',
 'MGVraepNj04',
 'Yb5D9Q4gZH8',
 'K_NRBkJtNAI',
 'nV-wPx3fRWE',
 'sbV_pDwKfZQ',
 'AfaIM7Ybwj4',
 'lfGeJHksykI',
 'ks219IgrXhM',
 'aOgBWl_kHYY',
 'PYY9VLOSLxk',
 'hT7Yd5nKMig',
 'YXy3emGbxHg',
 'jFS9rRTXue8',
 '7KwzVus9xds',
 'rZizVUKe4sQ',
 '_QgJKKHJU3Y',
 'hhBQ-sHYEtc',
 '0zMSMJZc9EA',
 'nYHDj2sB-rc',
 'kuYylDsN6KQ',
 '1A3QGAHZ6cI',
 '5JcZsNxT2BM',
 'MmHiZQRaso0',
 '-A3IlRATIsI',
 'LFvaD2d8Vd4',
 'DX0Dg9MxsOg',
 'X2bu3UjCxj0',
 'QgydTdThoeA',
 '_NSekwyS4Ns',
 'k6zVmxp6dOM',
 'el6No1wNKf0',
 'n1hR9rpvS74',
 'tOryRCeIAos',
 'ORmUUhh6O-8',
 'Wnv_JJIIxKk',
 'lO27dEaCS3c',
 'QOPZQHTNUs0',
 'DF-yBAkLFfw',
 'VZ5z7QflNEs',
 'pKmM1N0MoC4',
 'j5O2Od4bFdQ',
 'AlI9pMdhr0s']

In [3]:
def get_video_stats(video_id_list, youtube):

  video_data = []

  for item in video_id_list:
    request = youtube.videos().list(
        part = 'snippet,statistics',
        id = item
    )

    response = request.execute()
    video_data.append(
        {
            'channel_title': response['items'][0]['snippet']['channelTitle'],
            'category_id': response['items'][0]['snippet']['categoryId'],
            'view_count': response['items'][0]['statistics']['viewCount'],
            'like_count': response['items'][0]['statistics']['likeCount'],
            'comment_count': response['items'][0]['statistics']['commentCount']
        }
    )

  return video_data

sam_videos_data = get_video_stats(video_id_sam, youtube)

In [5]:
import pandas as pd
category_id_list = []
view_count_list = []
like_count_list = []
comment_count_list = []


for item in sam_videos_data:
    category_id_list.append(item.get('category_id'))
    view_count_list.append(item.get('view_count'))
    like_count_list.append(item.get('like_count'))
    comment_count_list.append(item.get('comment_count'))


df_sam_videos = pd.DataFrame({
    'Category ID': category_id_list,
    'View Count': view_count_list,
    'Like Count': like_count_list,
    'Comment Count': comment_count_list
})


df_sam_videos

   Category ID View Count Like Count Comment Count
0           24    4347873     387587         27849
1           24    7708071     501889         20904
2           24    4958976     399015         17261
3           24    6588444     477756         29517
4           24   12903312    1053831        127236
5           22   12628922     424328         49478
6           22   15453465     460147         14757
7           22   10239776     348023         10021
8           22   18087560     418222         13451
9           22   13230923     379888         11397
10          22   18298593     479536         11349
11          22   16487743     491816         16032
12          22   10920914     308094          7624
13          22   13854372     335701          8509
14          22   12903360     399076         12256
15          22   12244691     307822          8784
16          22   12117191     343891          9022
17          22   11929221     357217         15345
18          22          0         66             0
19          22   15635599     394760         16732
20          22   11610240     304327          9825
21          22   15658945     407685         13729
22          22   16562410     430508         13220
23          22    8742591     252208          6531
24          22   16367402     444844         11457
25          22   22512732     613029         16409
26          22   19270156     617094         25231
27          22   12493785     353690         10822
28          22   11257516     302248          8190
29          22   10978365     272910          6610
30          22   12622736     351350         20154
31          22   12635511     379198         10196
32          22   10857335     320849          7590
33          22    8322867     236565          7447
34          22   10159361     351015         12318
35          22   13628301     387108         16090
36          22    9445031     300169          7362
37          22   13121148     354006          6297
38          22   13439940     390988          9079
39          22   14292971     355430          7273
40          22     985623      42543          1573
41          22   19211884     514011         13062
42          22   14992501     437809         17587
43          22    9191890     288485          6553
44          22    8785471     233937          6888
45          22   11804548     284285          8296
46          22   10658985     285290          6908
47          22   14085401     340743         11269
48          22    7785990     263535          7646
49          22    6806678     231013          3640

In [8]:
df_sam_videos['Video_ids'] = video_id_sam

In [9]:
df_sam_videos.set_index('Video_ids', inplace=True)

In [10]:
df_sam_videos

            Category ID View Count Like Count Comment Count
Video_ids
5L5tjscy85U          24    4347873     387587         27849
4vvk7i-M6V0          24    7708071     501889         20904
FJwMDVrg8WU          24    4958976     399015         17261
wQmKqqsS-vs          24    6588444     477756         29517
XKRW1zgkCVc          24   12903312    1053831        127236
zz0PYzzfixY          22   12628922     424328         49478
ChSUvdU_Sbk          22   15453465     460147         14757
7s6VfSOuZpQ          22   10239776     348023         10021
MGVraepNj04          22   18087560     418222         13451
Yb5D9Q4gZH8          22   13230923     379888         11397
K_NRBkJtNAI          22   18298593     479536         11349
nV-wPx3fRWE          22   16487743     491816         16032
sbV_pDwKfZQ          22   10920914     308094          7624
AfaIM7Ybwj4          22   13854372     335701          8509
lfGeJHksykI          22   12903360     399076         12256
ks219IgrXhM          22   12244691     307822          8784
aOgBWl_kHYY          22   12117191     343891          9022
PYY9VLOSLxk          22   11929221     357217         15345
hT7Yd5nKMig          22          0         66             0
YXy3emGbxHg          22   15635599     394760         16732
jFS9rRTXue8          22   11610240     304327          9825
7KwzVus9xds          22   15658945     407685         13729
rZizVUKe4sQ          22   16562410     430508         13220
_QgJKKHJU3Y          22    8742591     252208          6531
hhBQ-sHYEtc          22   16367402     444844         11457
0zMSMJZc9EA          22   22512732     613029         16409
nYHDj2sB-rc          22   19270156     617094         25231
kuYylDsN6KQ          22   12493785     353690         10822
1A3QGAHZ6cI          22   11257516     302248          8190
5JcZsNxT2BM          22   10978365     272910          6610
MmHiZQRaso0          22   12622736     351350         20154
-A3IlRATIsI          22   12635511     379198         10196
LFvaD2d8Vd4          22   10857335     320849          7590
DX0Dg9MxsOg          22    8322867     236565          7447
X2bu3UjCxj0          22   10159361     351015         12318
QgydTdThoeA          22   13628301     387108         16090
_NSekwyS4Ns          22    9445031     300169          7362
k6zVmxp6dOM          22   13121148     354006          6297
el6No1wNKf0          22   13439940     390988          9079
n1hR9rpvS74          22   14292971     355430          7273
tOryRCeIAos          22     985623      42543          1573
ORmUUhh6O-8          22   19211884     514011         13062
Wnv_JJIIxKk          22   14992501     437809         17587
lO27dEaCS3c          22    9191890     288485          6553
QOPZQHTNUs0          22    8785471     233937          6888
DF-yBAkLFfw          22   11804548     284285          8296
VZ5z7QflNEs          22   10658985     285290          6908
pKmM1N0MoC4          22   14085401     340743         11269
j5O2Od4bFdQ          22    7785990     263535          7646
AlI9pMdhr0s          22    6806678     231013          3640

In [11]:
df_sam_videos.to_csv('sam_videos.csv')